'use strict';

module.exports = {
	up: function (queryInterface, Sequelize) {
		return queryInterface.bulkInsert('songs', [
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/01-Queen-Death On two Legs.mp3", name: "Death on Two Legs", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/02-Queen-Lazing On A Sunday Afternoon.mp3", name: "Lazing on a Sunday Afternoon", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/03-I'm In Love With My Car.mp3", name: "I'm In Love With My Car", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/04-Queen-You'e My Best Friend.mp3", name: "You're my Best Friend", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/05-Queen-'39.mp3", name: "'39", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/06-Queen-Sweet Lady.mp3", name: "Sweet Lady", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/07-Queen-Seaside Rendezvous.mp3", name: "Seaside Rendezvous", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/08-Queen-The Prophet's Song.mp3", name: "The Prophet's Song", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/09-Queen-Love Of My Life.mp3", name: "Love Of my Life", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/10-Queen-Good Company.mp3", name: "Good Cmopany", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/11-Queen-Bohemian Rhapsody.mp3", name: "Bohemian Rhapsody", },
			{ artistId: 1, albumId: 1, genreId: 1, moodId: 1, tag: "Vis", path: "/Queen - A Night At The Opera - MFSL GOLD UDCD 568/12-Queen-God Save The Queen.mp3", name: "God Save The Queen", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/01 - Book of Days.mp3", name: "Book of Days", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/02 - Wild Child.mp3", name: "Wild Child", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/03 - Boadicea.mp3", name: "Boadicea", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/04 - Storms in Africa.mp3", name: "Storms in Africa", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/05 - Caribbean Blue.mp3", name: "Caribbean Blue", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/06 - Tempus Vernum.mp3", name: "Tempus Vernum", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/07 - The Memory of Trees.mp3", name: "The Memory of Trees", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/08 - Lazy Days.mp3", name: "Lazy Days", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/09 - Shepherd Moons.mp3", name: "Shepherd Moons", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/10 - Cursum Perficio.mp3", name: "Cursum Perficio", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/11 - China Roses.mp3", name: "China Roses", },
			{ artistId: 2, albumId: 2, genreId: 1, moodId: 1, tag: "Vis", path: "/Vitamin String Quartet - Oceans- The String Quartet Tribute to Enya [Flac]/12 - Orinoco Flow.mp3", name: "Orinoco Flow", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/01 - Shepherd moons.mp3", name: "Shepherd moons", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/02 - Caribbean blue.mp3", name: "Caribbean Blue", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/03 - How can I keep from singing.mp3", name: "How Can I Keep From Singing", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/04 - Ebudae.mp3", name: "Ebudae", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/05 - Angeles.mp3", name: "Angeles", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/06 - No holly for Miss Quinn.mp3", name: "No Holly for Miss Quinn", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/07 - Book of days.mp3", name: "Book of Days", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/08 - Evacuee.mp3", name: "Evacuee", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/09 - Lothlorien.mp3", name: "Lothlorien", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/10 - Marble halls.mp3", name: "Marble Halls", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/11 - Afer ventus.mp3", name: "Afer Ventus", },
			{ artistId: 3, albumId: 3, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Shepherd Moons/12 - Smaointe....mp3", name: "Smaointe...", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/01 - Watermark.mp3", name: "Watermark", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/02 - Cursum Perficio.mp3", name: "Cusrum Perficio", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/03 - On Your Shore.mp3", name: "On Your Shore", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/04 - Storms In Africa.mp3", name: "Storms in Africa", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/05 - Exile.mp3", name: "Exile", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/06 - Miss Clare Remembers.mp3", name: "Miss Clare Remembers", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/07 - Orinoco Flow.mp3", name: "Orinoco Flow", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/08 - Evening Falls....mp3", name: "Evening Falls...", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/09 - River.mp3", name: "River", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/10 - The Longships.mp3", name: "The Longships", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/11 - Na Laetha Geal M'óige.mp3", name: "Na Laetha Geal M'óige", },
			{ artistId: 3, albumId: 4, genreId: 5, moodId: 1, tag: "Vis", path: "/Enya - Watermark/12 - Storms In Africa (Part II).mp3", name: "Storms in Africa (Part 2)", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/01 - Queen B.mp3", name: "Queen B", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/02 - DoZo [Version 3].mp3", name: "Dozo", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/03 - Vagina Mine.mp3", name: "Vagina Mine", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/04 - Momma Sed.mp3", name: "Momma Sed", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/05 - Drunk With Power [Version 2].mp3", name: "Drink with Power", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/06 - The Undertaker.mp3", name: "The Undertaker", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/07 - Trekka.mp3", name: "Trekka", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/08 - Indigo Children.mp3", name: "Indigo Children", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/09 - Sour Grapes.mp3", name: "Sour Grapes", },
			{ artistId: 4, albumId: 5, genreId: 4, moodId: 1, tag: "Vis", path: "/Puscifer - 'V' is for Vagina [2007]/10 - Rev 22-30 [Dry Martini Mix].mp3", name: "Rev 22-30", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/01 - E. S. Posthumus - Kalki.mp3", name: "Kalki", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/02 - E. S. Posthumus - Varuna.mp3", name: "Varuna", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/03 - E. S. Posthumus - Unstoppable.mp3", name: "Unstoppable", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/04 - E. S. Posthumus - Durga.mp3", name: "Durga", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/05 - E. S. Posthumus - Manju.mp3", name: "Manju", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/06 - E. S. Posthumus - Kuvera.mp3", name: "Kuvera", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/07 - E. S. Posthumus - Ushas.mp3", name: "Ushas", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/08 - E. S. Posthumus - Lavanya.mp3", name: "Lavanya", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/09 - E. S. Posthumus - Vishnu.mp3", name: "Vishnu", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/10 - E. S. Posthumus - Indra.mp3", name: "Indra", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/11 - E. S. Posthumus - Arise.mp3", name: "Arisu", },
			{ artistId: 6, albumId: 7, genreId: 7, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/12 - E. S. Posthumus - Saint Matthew Passion.mp3", name: "Saint Matthew Passion", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/13 - E. S. Posthumus - Krosah.mp3", name: "Krosah", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/14 - E. S. Posthumus - Anumati.mp3", name: "Anumati", },
			{ artistId: 6, albumId: 7, genreId: 6, moodId: 1, tag: "Vis", path: "/E. S. Posthumus - Makara/15 - E. S. Posthumus - Moonlight Sonata.mp3", name: "Moonlight Sonata", },
			{ artistId: 11, albumId: 12, genreId: 4, moodId: 1, tag: "Vis", path: "/[2012]  Weightless/01. Marconi Union - Weightless Part 1.mp3", name: "Weightless (Part 1)", },
			{ artistId: 11, albumId: 12, genreId: 4, moodId: 1, tag: "Vis", path: "/[2012]  Weightless/01. Marconi Union - Weightless Part 2.mp3", name: "Weightless (Part 2)", },
			{ artistId: 11, albumId: 12, genreId: 4, moodId: 1, tag: "Vis", path: "/[2012]  Weightless/01. Marconi Union - Weightless Part 3.mp3", name: "Weightless (Part 3)", },
			{ artistId: 11, albumId: 12, genreId: 4, moodId: 1, tag: "Vis", path: "/[2012]  Weightless/01. Marconi Union - Weightless Part 4.mp3", name: "Weightless (Part 4)", },
			{ artistId: 11, albumId: 12, genreId: 4, moodId: 1, tag: "Vis", path: "/[2012]  Weightless/01. Marconi Union - Weightless Part 5.mp3", name: "Weightless (Part 5)", },
			{ artistId: 11, albumId: 12, genreId: 4, moodId: 1, tag: "Vis", path: "/[2012]  Weightless/01. Marconi Union - Weightless Part 6.mp3", name: "Weightless (Part 6)", },
		]);
	},

	down: function (queryInterface, Sequelize) {
		return queryInterface.bulkDelete("songs");
	}
};
